on

diff --git a/.github/workflows/valgrind.yml b/.github/workflows/valgrind.yml
--- a/.github/workflows/valgrind.yml
+++ b/.github/workflows/valgrind.yml
@@ -22,15 +22,15 @@ jobs:
           fi
           exit 1        
 
-      - name: test fail 
-        shell: bash
-        run: |
-          echo "ASDF" > logfile
-          OUTPUT='ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)'
-          if grep -q "$OUTPUT" logfile; then
-            exit 0
-          fi
-          exit 1
+      # - name: test fail 
+      #   shell: bash
+      #   run: |
+      #     echo "ASDF" > logfile
+      #     OUTPUT='ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)'
+      #     if grep -q "$OUTPUT" logfile; then
+      #       exit 0
+      #     fi
+      #     exit 1
 
       - name: Install Valgrind
         run: sudo apt-get update && sudo apt-get install valgrind
